(defparameter *drink-order* '((bill . double-espresso)
                              (lisa . small-drip-coffee)
                              (john . medium-latte)))
(cdr (assoc 'lisa *drink-order*))
(push '(lisa . large-mocha-with-whipped-cream) *drink-order*)
(cdr (assoc 'lisa *drink-order*))

(defparameter *house* '((walls (mortar (cement)
                                (water)
                                (sand))
                         (bricks))
                        (windows (glass)
                         (frame)
                         (cutains))
                        (roof (shingles)
                         (chimney))))

(defparameter *h-drink-order* (make-hash-table))
(setf (gethash 'bill *h-drink-order*) 'double-espresso)
(setf (gethash 'lisa *h-drink-order*) 'small-drip-coffee)
(setf (gethash 'jogn *h-drink-order*) 'medium-latte)
(gethash 'lisa *h-drink-order*)
