(defparameter *drink-order* '((bill . double-espresso)
                              (lisa . small-drip-coffee)
                              (john . medium-latte)))
(cdr (assoc 'lisa *drink-order*))
(push '(lisa . large-mocha-with-whipped-cream) *drink-order*)
(cdr (assoc 'lisa *drink-order*))

(defparameter *house* '((walls (mortar (cement)
                                (water)
                                (sand))
                         (bricks))
                        (windows (glass)
                         (frame)
                         (cutains))
                        (roof (shingles)
                         (chimney))))